server:
  port: 8085

spring:
  application:
    name: ms-inventario
  datasource:
    url: jdbc:mysql://98.89.176.25:3306/db_inventario?createDatabaseIfNotExist=true
    username: admin
    password: modeltoys
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/